//! The window icon every Kóoch window carries.
//!
//! Lives here rather than in the editor so a **game** built on the engine
//! gets it too. Wired into `kooch_editor` it would be the editor's icon;
//! wired here it is the engine's, and a project that wants its own
//! replaces one rather than adding the first.
//!
//! # Why the myth variant and not the debug one
//!
//! The formal logo is `kooch_debug.svg` — a teardrop tessellated into
//! cluster-coloured meshlets, which is the engine's own visibility-buffer
//! debug view and the reason the mark means anything at all. It is also,
//! in the logo generator's own words, *"rainbow mush below ~48px"*.
//!
//! A title-bar icon is 16 to 32 px on most desktops. `kooch_myth.svg`
//! ramps one hue from dark to light, so the silhouette survives at that
//! size. Same drop, same myth — Kóoch wept the sea into being. Chosen per
//! size, not per preference. Both live in `docs/brand/`, generated by the
//! script beside them.

use winit::window::Icon;

/// 64×64 RGBA, rendered from `docs/brand/kooch_myth.svg`.
///
/// Larger than a title bar needs: window managers downscale for the title
/// bar and use the full size for the task switcher, and downscaling from
/// 64 beats upscaling from 32.
const ICON_PNG: &[u8] = include_bytes!("../icon/kooch-64.png");

const ICON_SIZE: u32 = 64;

/// Decodes the embedded icon.
///
/// Returns `None` rather than panicking. A window with no icon is a
/// cosmetic loss; refusing to open one over it would trade the
/// application for a decoration.
pub fn window_icon() -> Option<Icon> {
    let decoded = match image::load_from_memory_with_format(ICON_PNG, image::ImageFormat::Png) {
        Ok(image) => image.to_rgba8(),
        Err(err) => {
            tracing::warn!("window icon failed to decode ({err}); running without one");
            return None;
        }
    };
    let (width, height) = decoded.dimensions();
    match Icon::from_rgba(decoded.into_raw(), width, height) {
        Ok(icon) => Some(icon),
        Err(err) => {
            tracing::warn!("window icon rejected by winit: {err}");
            None
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A teardrop on transparency: corners empty, middle not. Catches a
    /// decode that "succeeds" into garbage, which a length check alone
    /// would pass — and catches someone replacing the file with a
    /// square logo that fills the whole tile.
    #[test]
    fn the_embedded_icon_is_a_mark_on_transparency() {
        let image = image::load_from_memory_with_format(ICON_PNG, image::ImageFormat::Png)
            .expect("the icon shipped in this crate must decode")
            .to_rgba8();
        assert_eq!(image.dimensions(), (ICON_SIZE, ICON_SIZE));

        let alpha = |x: u32, y: u32| image.get_pixel(x, y).0[3];
        assert_eq!(alpha(0, 0), 0, "top-left corner should be transparent");
        assert_eq!(
            alpha(ICON_SIZE - 1, 0),
            0,
            "top-right corner should be transparent",
        );
        assert!(
            alpha(ICON_SIZE / 2, ICON_SIZE / 2) > 200,
            "the centre of the drop should be opaque",
        );
    }

    #[test]
    fn winit_accepts_it() {
        assert!(window_icon().is_some(), "winit rejected the icon");
    }
}
