//! Physical intent, never simulation details. Reflection has no enums
//! ([`ReflectValue`](kooch_ecs::reflect::ReflectValue)), so variants are `u32` choices with flat
//! fields, resolved to typed enums at the seam; hiding is display only.

mod body;
mod joint;

pub use body::{
    BORDER_RADIUS_WHEN, CENTER_OF_MASS_WHEN, COMBINE_AVERAGE, COMBINE_CHOICES, COMBINE_CLAMPED_SUM,
    COMBINE_MAX, COMBINE_MIN, COMBINE_MULTIPLY, CONTACT_FORCE_WHEN, Collider, ENDPOINTS_WHEN,
    HALF_EXTENTS_WHEN, HALF_HEIGHT_WHEN, KIND_CHOICES, KIND_DYNAMIC, KIND_KINEMATIC, KIND_STATIC,
    MESH_DERIVED, MESH_WHEN, NORMAL_WHEN, POINT_C_WHEN, PhysicsBody, RADIUS_WHEN, SHAPE_CAPSULE,
    SHAPE_CHOICES, SHAPE_CONE, SHAPE_CONVEX_DECOMPOSITION, SHAPE_CONVEX_HULL, SHAPE_CUBOID,
    SHAPE_CYLINDER, SHAPE_HALF_SPACE, SHAPE_OWN_MESH, SHAPE_POLYLINE, SHAPE_ROUND_CYLINDER,
    SHAPE_SEGMENT, SHAPE_SPHERE, SHAPE_TRIANGLE, SHAPE_TRIMESH, SHAPE_VOXELIZED_MESH, SHAPE_VOXELS,
    ShapeSpec, VOXEL_SIZE_WHEN, VOXEL_SOLID_WHEN, is_mesh_derived,
};
pub use joint::{
    AXIS_WHEN, BREAKABLE_WHEN, FREE_AXIS_WHEN, JOINT_FIXED, JOINT_GENERIC, JOINT_KIND_CHOICES,
    JOINT_PIN_SLOT, JOINT_PRISMATIC, JOINT_REVOLUTE, JOINT_ROPE, JOINT_SPHERICAL, JOINT_SPRING,
    Joint, LOCKED_AXES_WHEN, MAX_LENGTH_WHEN, MOTOR_ACCELERATION, MOTOR_FORCE, MOTOR_MODEL_CHOICES,
    SPRING_WHEN,
};
