//! The files a new project starts with: its Cargo.toml, lib.rs, main.rs, the editor binary and .gitignore.

use super::*;

/// Generates a `Cargo.toml` for a project crate.
#[cfg(test)]
pub(crate) fn generate_cargo_toml_for_test(name: &str, engine_path: &str) -> String {
    generate_cargo_toml(name, engine_path)
}

pub(super) fn generate_cargo_toml(name: &str, engine_path: &str) -> String {
    let crate_name = sanitize_crate_name(name);
    // Cargo.toml requires forward slashes even on Windows.
    let engine_path = engine_path.replace('\\', "/");
    format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

[workspace]

# 🔴 A shipped game must not contain the editor (#558).
#
# `editor` is opt-in and the authoring binary below asks for it with
# `required-features`, so `cargo build --release` produces the game and
# cargo never puts the editor in its dependency graph at all. The
# guarantee belongs to the build, not to a `cfg` somebody has to get
# right — and `cargo tree` will show you.
#
# `physics` gives you rigid bodies: without it a `PhysicsBody` is an inert
# component and nothing ever falls. `gravity` is the same story one level
# up — a `PointGravity` is authorable, draws its gizmo, and pulls on
# nothing. `camera` is the third: a `VirtualCamera` that moves no camera.
[features]
default = ["game"]
game = ["kooch/physics", "kooch/gravity", "kooch/camera", "kooch/audio"]
# `dynamic` is what lets the standalone editor load this project's
# component types without compiling them; `remote` is how it drives them
# over a local socket; `physics-debug-render` compiles the solver walk the
# editor's overlay draws (#634). A game needs none of the three.
editor = [
    "game",
    "kooch/editor",
    "kooch/remote",
    "kooch/dynamic",
    "kooch/physics-debug-render",
]

# Two artefacts from one crate. The `dylib` is what the standalone editor
# loads to learn this project's component types without compiling them;
# the `rlib` beside it is what the binaries below link, so the game is an
# ordinary statically linked executable.
[lib]
crate-type = ["rlib", "dylib"]

# The game. No flags, no modes: double-clicking this plays.
[[bin]]
name = "{crate_name}"
path = "src/main.rs"

# Authoring — the embedded editor and the remote host. A separate target
# so a game build does not produce it, and `required-features` so a game
# build cannot.
[[bin]]
name = "{crate_name}_editor"
path = "src/editor.rs"
required-features = ["editor"]

[dependencies]
kooch = {{ path = "{engine_path}" }}
# Direct dep needed until `Reflect` proc-macro resolves through the facade.
kooch_ecs = {{ path = "{engine_path}/crates/kooch_ecs" }}
{profile}"#,
        profile = dev_profile::DEV_PROFILE,
    )
}

/// Generates `src/lib.rs` — the project as a library the editor loads.
pub(crate) fn generate_lib_rs(name: &str) -> String {
    let crate_name = sanitize_crate_name(name);
    format!(
        r##"//! AUTO-GENERATED by the Kóoch editor — do not edit by hand.
//! Your project, as a library the editor can load. The `dylib` this produces is what lets the
//! standalone editor list your components without compiling them.

// Editor-managed module: declares your components + systems.
pub mod registrations;

// Everything below exists so the standalone editor can list your components without compiling them,
// and it is compiled out of a game build along with the rest of the authoring surface (#558) — a
// game loads no plugins, and `kooch::kooch_plugin_api` is not in its dependency graph to name.
#[cfg(feature = "editor")]
mod plugin {{
    use super::registrations;

    /// Declares this project's component types to the editor.
    #[derive(Default)]
    pub struct ProjectPlugin;

    impl kooch::kooch_plugin_api::KoochPlugin for ProjectPlugin {{
        fn name(&self) -> &str {{
            "{crate_name}"
        }}

        fn build(&mut self, engine: &mut dyn kooch::kooch_plugin_api::Engine) {{
            registrations::declare_components(engine);
        }}
    }}

    kooch::kooch_plugin_api::export_plugin!(ProjectPlugin);
}}

#[cfg(feature = "editor")]
pub use plugin::ProjectPlugin;
"##
    )
}

/// Generates a scaffold `src/main.rs` for a project crate.
pub(crate) fn generate_main_rs(name: &str) -> String {
    let crate_name = sanitize_crate_name(name);
    r##"//! Your game.
//! No flags and no modes: this is what a player runs, and it is the whole of what a shipped build
//! contains. Authoring lives in `src/editor.rs`, behind the `editor` feature, so this binary cannot
//! link it (#558).

use kooch::prelude::*;

// The project's own library — the same code the editor loads as a dylib.
// `registrations` is editor-managed: regenerated whenever you create or
// register scripts. Do not edit it by hand.
use PROJECT_CRATE::registrations;

fn main() {
    let mut app = App::new();
    app.add_plugins(DefaultPlugins);
    app.add_plugin(registrations::ProjectRegistrations { run_systems: true });
    app.run();
}
"##
    .replace("PROJECT_CRATE", &crate_name)
}

/// Generates `src/editor.rs` — authoring, in a target a game build does not produce.
pub(crate) fn generate_editor_rs(name: &str) -> String {
    let crate_name = sanitize_crate_name(name);
    r##"//! Authoring: the editor, and the host the standalone editor drives.
//!
//! Built only with `--features editor` (see `Cargo.toml`), so nothing
//! here can reach a shipped game.

use kooch::prelude::*;

use PROJECT_CRATE::registrations;

fn main() {
    // `cargo run --features editor --bin PROJECT_CRATE_editor` → the editor, with your components.
    // `… -- --remote` → headless authoring host: your components + the remote server, driven by the
    // standalone editor over a local socket.
    let args: Vec<String> = std::env::args().collect();
    if args.iter().any(|a| a == "--remote") {
        // Headless on purpose: the editor draws this world in its own
        // viewport, so a window here would show the same scene twice.
        let mut app = App::new();
        app.add_plugins(RemoteHostPlugins);
        app.add_plugin(registrations::ProjectRegistrations { run_systems: false });
        app.add_plugin(kooch::kooch_remote::RemotePlugin::new());
        app.run();
    } else {
        // Components register (so the Inspector sees them); gameplay
        // systems do not run until Play.
        kooch::kooch_editor_core::run_editor_with(registrations::ProjectRegistrations {
            run_systems: false,
        });
    }
}
"##
    .replace("PROJECT_CRATE", &crate_name)
}

/// Contents of a fresh, empty `src/registrations.rs` — valid on its own so a new project compiles
/// before any component/system exists. The editor overwrites it with real registrations via
/// `crate::actions::codegen`.

/// Creates a new project directory with the standard structure and manifest.

/// What a new project tells git to leave alone.
pub(super) const PROJECT_GITIGNORE: &str = "\
# Rust build output. Gigabytes, and every byte of it regenerable.
/target

# 🔴 Editor-owned local state, and it holds this project's asset pack
# key. A repository that carries one has published it, and history keeps
# it published after the file is deleted. Keep a copy somewhere else:
# without it nobody can open the packs you already shipped.
/.kooch


# rustfmt leftovers.
**/*.rs.bk

# OS clutter.
.DS_Store
Thumbs.db
";
