[package]
name = "ome_render"
description = "Clear-color renderer for oh_my_engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
ome_core.workspace = true
wgpu.workspace = true
tracing.workspace = true
