[package]
name = "ome_editor_core"
description = "Embedded editor overlay (debug visualization, inspector)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
ome_core.workspace = true
ome_ecs.workspace = true
ome_window.workspace = true
egui.workspace = true
egui-winit.workspace = true
egui-wgpu.workspace = true
winit.workspace = true
wgpu.workspace = true
tracing.workspace = true
