//! Keeping `registrations.rs` level with `src/`, without being told.
//!
//! # The gap this closes
//!
//! `registrations.rs` is generated by scanning `src/`, and until now the
//! only things that triggered that scan were editor actions: creating a
//! script, renaming one, or the entry buried in the asset browser's
//! context menu. Write a system in an external editor and nothing ran —
//! so the system was never registered, never executed, and **nothing
//! said so**. Not a warning, not a log line. It simply did not happen.
//!
//! # Why it polls instead of watching
//!
//! Not a compromise. This user's projects live on an NTFS volume mounted
//! through FUSE, where **inotify silently drops events** — a watcher
//! there is a mechanism that appears to work and misses changes, which
//! is a worse failure than no watcher at all because it is trusted. A
//! poll on a timer cannot miss anything; it can only be late.
//!
//! # Two tiers, because the exact answer is not free
//!
//! The precise test is `render(scan(src)) == what is on disk` — exact,
//! with no false positives even for a comment edit. It also reads every
//! `.rs` file in the project, which is not something to do twice a
//! second on a FUSE mount. So a cheap fingerprint (newest mtime, file
//! count) gates it: the tree has to move before anything is read.

use std::path::Path;
use std::time::{Duration, Instant};

use kooch_core::resource::Resources;

use crate::actions::{SyncOutcome, register_scripts};
use crate::project_state::ProjectState;

/// How often the fingerprint is taken. Fast enough that saving in
/// another window and alt-tabbing back finds it already done, slow
/// enough that a `stat` per file is nothing.
const POLL: Duration = Duration::from_millis(750);

/// Whether the generated registrations match `src/`, and whether the
/// running project matches them.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub enum SyncState {
    /// Nothing to report: the file is current and no rewrite has
    /// happened since the project was last built.
    #[default]
    Current,
    /// The file was rewritten, so the project's compiled code is now
    /// behind its source. Cleared by a rebuild, or by the author
    /// acknowledging it.
    ///
    /// 🔴 This is the state worth showing, and it is NOT "the file is
    /// stale" — the file is fixed by then. What is stale is the build:
    /// the editor loads the project's compiled dylib, so a component
    /// added five seconds ago exists in `registrations.rs` and in no
    /// binary anywhere. Announcing the file would announce something
    /// already handled; announcing the build names what the author still
    /// has to do.
    NeedsRebuild,
}

/// The poll's state between frames.
#[derive(Default)]
pub struct ScriptSync {
    /// When the fingerprint may be taken again.
    next_poll: Option<Instant>,
    /// Newest modification time in `src/`, and how many files it saw.
    ///
    /// The count is there because mtime alone cannot see a deletion:
    /// removing the newest file leaves an older maximum, which reads as
    /// "nothing changed since" while a system just disappeared.
    fingerprint: Option<(Duration, usize)>,
    pub state: SyncState,
}

impl ScriptSync {
    /// The author has seen it. Also what a rebuild calls.
    pub fn acknowledge(&mut self) {
        self.state = SyncState::Current;
    }
}

/// Newest mtime and file count under `src/`, or `None` if it cannot be
/// read.
///
/// 🔴 `registrations.rs` is excluded, and it has to be: it is the file
/// this writes. Counting it would make every regeneration move the
/// fingerprint, which would schedule the next scan, which would find
/// nothing to change — a full read of the tree after every save, for
/// nothing.
fn fingerprint(src: &Path) -> Option<(Duration, usize)> {
    fn walk(dir: &Path, newest: &mut Duration, count: &mut usize) {
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                walk(&path, newest, count);
                continue;
            }
            if path.extension().is_none_or(|ext| ext != "rs") {
                continue;
            }
            if path.file_name().is_some_and(|n| n == "registrations.rs") {
                continue;
            }
            *count += 1;
            let Ok(modified) = entry.metadata().and_then(|m| m.modified()) else {
                continue;
            };
            if let Ok(since) = modified.duration_since(std::time::UNIX_EPOCH) {
                *newest = (*newest).max(since);
            }
        }
    }
    if !src.is_dir() {
        return None;
    }
    let mut newest = Duration::ZERO;
    let mut count = 0;
    walk(src, &mut newest, &mut count);
    Some((newest, count))
}

/// Regenerates `registrations.rs` when `src/` has moved under it.
///
/// Registered in `PreUpdate`. Costs a `stat` per source file every
/// [`POLL`], and reads nothing at all until that fingerprint changes.
pub fn sync_scripts_system(resources: &mut Resources) {
    let now = Instant::now();
    let Some(sync) = resources.get_mut::<ScriptSync>() else {
        return;
    };
    if sync.next_poll.is_some_and(|next| now < next) {
        return;
    }
    sync.next_poll = Some(now + POLL);

    let Some(src) = resources
        .get::<ProjectState>()
        .and_then(|ps| ps.active_project.as_ref())
        .map(|active| active.root_path.join("src"))
    else {
        return;
    };
    let Some(taken) = fingerprint(&src) else {
        return;
    };
    let Some(sync) = resources.get_mut::<ScriptSync>() else {
        return;
    };
    // 🔴 A first sighting is recorded, never acted on. Opening a project
    // would otherwise regenerate on the first frame and announce a
    // rebuild for a file that was already correct.
    let known = sync.fingerprint.replace(taken);
    if known.is_none_or(|last| last == taken) {
        return;
    }

    if register_scripts(resources) == SyncOutcome::Regenerated
        && let Some(sync) = resources.get_mut::<ScriptSync>()
    {
        sync.state = SyncState::NeedsRebuild;
    }
}

#[cfg(test)]
mod tests;
