//! Renders the text of the project's `src/registrations.rs`.

use std::collections::BTreeSet;

use super::SourceFile;

/// Renders the whole of `registrations.rs`.
pub(super) fn render_registrations(files: &[SourceFile]) -> String {
    // Every `use` and every binding below is emitted only when something reads it.
    let has_components = files.iter().any(|f| !f.components.is_empty());

    let mut s = String::new();
    s.push_str("// AUTO-GENERATED by the Kóoch editor — do not edit by hand.\n");
    s.push_str("// Regenerated when you create or register components / systems.\n\n");
    if has_components {
        s.push_str("use kooch::kooch_ecs::component::ComponentRegistry;\n");
    }
    s.push_str("use kooch::prelude::*;\n\n");
    s.push_str(&render_modules(files));
    s.push('\n');
    s.push_str("/// Editor-managed plugin: registers project components + systems.\n");
    s.push_str("///\n");
    s.push_str("/// A system binds to `Stage::Update` wrapped in `run_if_playing`\n");
    s.push_str("/// unless its `#[system(...)]` says otherwise — `#[system(PreUpdate)]`\n");
    s.push_str("/// moves it, `always` drops the wrapper for the systems that must\n");
    s.push_str("/// run while the editor is paused.\n");
    s.push_str("///\n");
    s.push_str("/// `run_if_playing` reads the `Playing` resource per frame, so\n");
    s.push_str("/// `run_systems` only sets its starting value: `true` in the game\n");
    s.push_str("/// build, `false` while editing — and the editor's Play button\n");
    s.push_str("/// flips it live, with no rebuild.\n");
    s.push_str("pub struct ProjectRegistrations {\n");
    s.push_str("    pub run_systems: bool,\n");
    s.push_str("}\n\n");
    s.push_str("impl Plugin for ProjectRegistrations {\n");
    // So the editor's system panel can tell a project system from an
    // engine one. Declared here because a plugin is the only thing that
    // knows which side it is on (#982).
    s.push_str("    fn source(&self) -> SystemSource {\n");
    s.push_str("        SystemSource::Project\n");
    s.push_str("    }\n\n");
    s.push_str("    fn build(&self, app: &mut App) {\n");
    s.push_str("        app.insert_resource(Playing(self.run_systems));\n");
    s.push_str("        app.add_system(Stage::Startup, register_components);\n");
    for f in files {
        for sys in &f.systems {
            let call = match sys.gated {
                true => format!("run_if_playing({}::{})", f.module, sys.name),
                false => format!("{}::{}", f.module, sys.name),
            };
            s.push_str(&format!(
                "        app.add_system(Stage::{}, {});\n",
                sys.stage, call
            ));
        }
    }
    s.push_str("    }\n}\n\n");
    s.push_str("/// Registers project components for serialization + the Inspector.\n");
    s.push_str("fn register_components(resources: &mut Resources) {\n");
    if has_components {
        s.push_str("    let Some(registry) = resources.get_mut::<ComponentRegistry>() else {\n");
        s.push_str("        return;\n");
        s.push_str("    };\n");
        for f in files {
            for c in &f.components {
                s.push_str(&format!(
                    "    registry.register_cpu_reflected::<{}::{}>();\n",
                    f.module, c
                ));
            }
        }
    } else {
        // Nothing to register: binding `registry` would be an unused
        // variable, and this file no longer silences that.
        s.push_str("    let _ = resources;\n");
    }
    s.push_str("}\n\n");

    // The other direction: describing these same types outward, so the
    // standalone editor can list them without compiling them. The engine
    // reads each type's own reflection, so this only has to name them.
    s.push_str("/// Describes project components to an editor that loads this library.\n");
    s.push_str("///\n");
    s.push_str("/// Called from `lib.rs` when the editor loads the project's dylib.\n");
    // 🔴 Behind the `editor` feature, like the export in `lib.rs`. It names
    // `kooch::kooch_plugin_api` and `component::plugin_bridge`, both of which live behind `dynamic`
    // — which a game build does not enable (#558).
    s.push_str("#[cfg(feature = \"editor\")]\n");
    s.push_str("pub fn declare_components(engine: &mut dyn kooch::kooch_plugin_api::Engine) {\n");
    if !has_components {
        // No components to describe. Binding the parameter keeps a project
        // with none of its own components warning-free without reaching
        // for a blanket `allow` — see the note at the top of this function.
        s.push_str("    let _ = engine;\n");
    } else {
        s.push_str("    use kooch::kooch_ecs::component::plugin_bridge::declare_component;\n");
        for f in files {
            for c in &f.components {
                s.push_str(&format!(
                    "    let _ = declare_component::<{}::{}>(engine);\n",
                    f.module, c
                ));
            }
        }
    }
    s.push_str("}\n");
    s
}

/// Emits the module declarations, nesting them to match `src/`.
fn render_modules(files: &[SourceFile]) -> String {
    let mut s = String::new();
    let mut open: Vec<&str> = Vec::new();

    for f in files {
        let dirs = f.directories();
        let shared = open
            .iter()
            .zip(dirs.iter())
            .take_while(|(a, b)| a == b)
            .count();

        while open.len() > shared {
            open.pop();
            s.push_str(&format!("{}}}\n", indent(open.len())));
        }
        for dir in &dirs[shared..] {
            let pad = indent(open.len());
            // The container carries the directory; its children then only
            // have to name their own file.
            s.push_str(&format!("{pad}#[path = \"{dir}\"]\n"));
            s.push_str(&format!("{pad}pub mod {} {{\n", sanitize(dir)));
            open.push(dir);
        }

        let pad = indent(open.len());
        // Public throughout, so `main.rs` can reach a project's own code.
        let vis = "pub mod";
        s.push_str(&format!("{pad}#[path = \"{}\"]\n", f.file_name()));
        s.push_str(&format!("{pad}{vis} {};\n", sanitize(f.stem())));
    }

    while let Some(_) = open.pop() {
        s.push_str(&format!("{}}}\n", indent(open.len())));
    }
    s
}

fn indent(depth: usize) -> String {
    "    ".repeat(depth)
}

/// Turns one path segment into a usable module identifier.
pub(super) fn sanitize(segment: &str) -> String {
    // `crate`, `self`, `super` and `Self` cannot be raw identifiers, so
    // they get a suffix instead. Everything else that clashes is spelled
    // `r#…` and keeps its name.
    const UNRAWABLE: &[&str] = &["crate", "self", "super", "Self"];
    const KEYWORDS: &[&str] = &[
        "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "do",
        "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "gen", "if", "impl", "in",
        "let", "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref",
        "return", "static", "struct", "trait", "true", "try", "type", "typeof", "unsafe",
        "unsized", "use", "virtual", "where", "while", "yield",
    ];

    let mut out: String = segment
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect();
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    if UNRAWABLE.contains(&out.as_str()) {
        out.push('_');
    } else if KEYWORDS.contains(&out.as_str()) {
        out.insert_str(0, "r#");
    }
    out
}

/// The Rust path a source file is reachable at, e.g. `components::movement`.
pub(super) fn module_path(rel: &str) -> String {
    let stem = rel.strip_suffix(".rs").unwrap_or(rel);
    stem.split('/').map(sanitize).collect::<Vec<_>>().join("::")
}

/// Names claimed by both a file and a directory, e.g. `src/components.rs` beside `src/components/`.
pub(super) fn colliding_names(files: &[SourceFile]) -> Vec<String> {
    let mut dirs: BTreeSet<String> = BTreeSet::new();
    let mut leaves: BTreeSet<String> = BTreeSet::new();
    for f in files {
        let segments: Vec<&str> = f.rel.split('/').collect();
        for (depth, segment) in segments.iter().enumerate() {
            let path = segments[..depth].join("/");
            let qualified = if path.is_empty() {
                (*segment).to_owned()
            } else {
                format!("{path}/{segment}")
            };
            if depth + 1 == segments.len() {
                leaves.insert(qualified.trim_end_matches(".rs").to_owned());
            } else {
                dirs.insert(qualified);
            }
        }
    }
    dirs.intersection(&leaves).cloned().collect()
}
